<?php
require_once('./dbconfig.php');
session_start();
$sql="SELECT * FROM user WHERE `UserID` ='".$_SESSION['uid']."'";   // get user name
$result=mysqli_query($db_connection,$sql);
$row_result = mysqli_fetch_assoc($result);

$sqlInventory="SELECT * FROM inventory";    // get data from inventory
$result_invent=mysqli_query($db_connection,$sqlInventory);
$counter=1;
$zero=0;

$date=$_SESSION['report'];
?>

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="../css/header.css" />
        <link rel="stylesheet" type="text/css" href="../css/report4.css" />
        <title>Reporting System</title>
    </head>
    <body>
        <div class="header">
            <img src="../img/logo.png" alt="Logo">
            <h1>Inventory System</h1>
        </div>
        <div class="refLink">
            <h2> Report System</h2>
            <a href="./homepage.php">Home Page</a><p>&nbsp>&nbsp</p><a href="./ReportSystem.php">Report System</a>
                <p>&nbsp>&nbsp</p><p>
                  <?php if($date==date('Y')."-01-01")
                      echo "Annual Report";
                  else if($date==date('Y-m')."-01")
                      echo "Monthly Report";
                  else if($date==date('Y-m-d'))
                      echo "Daily Report";
                  ?>
                </p>
        </div>
        <hr>
        <div><a href="./ReportSystem.php"><input type="button" class="back" value="<< Back" /></a></div>
        <div class=body>
            <div>
                <p>GENERATED BY: <?php echo $row_result['Name']; ?></p><br>
                <p id="padding"><?php
                    if($date==date('Y')."-01-01")
                        echo "DATE RANGE : 01/01/".date('Y')." - ".date('d/m/Y');
                    else if($date==date('Y-m')."-01")
                        echo "DATE RANGE : 01/".date('m/Y')." - ".date('d/m/Y');
                    else if($date==date('Y-m-d'))
                        echo "DATE RANGE : ".date('d/m/Y');
                    ?>
                </p>

                <table>
                    <tr>
                        <th style="width:50px "scope="col">No.</th>
                        <th style="width:300px" scope="col">Item</th>
                        <th style="width:200px"scope="col">Total Amount</th>
                        <th style="width:200px"scope="col">Borrow Amount</th>
                    </tr>
                    <?php while($row=mysqli_fetch_assoc($result_invent)){ ?>
                    <tr>
                        <td><?php echo $counter; $counter++; ?></td>
                        <td><?php echo $row['ItemName']; ?></td>
                        <td><?php echo $row['ItemAmount']; ?></td>
                        <td><?php echo $row['BorrowAmount']; ?> </td>
                    </tr>
                    <?php } ?>
                </table>
            </div>
            <div class="gridcontainer">
                <div class="item1">
                     <?php $sqlLost="SELECT * FROM itemreturn WHERE `ItemLoss` >'".$zero."' AND `ReturnDate`>= '".$date."'";
                     $lost = mysqli_query($db_connection,$sqlLost);
                     $dataRow =mysqli_num_rows($lost);
                     $num=0;
                     $totalLoss=0;
                     if($dataRow>0)
                     {
                       while($num<$dataRow){
                         $fetch = mysqli_fetch_assoc($lost);
                         $totalLoss += $fetch['ItemLoss'];
                         $num++;
                       }
                       echo "Total item loses: ".$totalLoss;
                     }
                     else {
                        echo "Total item loses: ".$zero;
                     }
                    ?>
                </div>
                <div class="item2"><a href="ItemLost.php"><input type="button" class="check" value="Check"/></a></div>
                <div class="item3"><?php
                      $latesql = "SELECT *from itemreturn inner join application on itemreturn.AppID=application.ApplicationID   where itemreturn.ReturnDate >=application.ReturnDate and application.`Status`='approved' and itemreturn.ReturnDate >= '".$date."'";
                      $late=mysqli_query($db_connection,$latesql);
                      $latenum = mysqli_num_rows($late);
                      if($latenum>0){
                          echo "Total item late return case: ".$latenum;
                      }
                      else {
                          echo "Total item late return case: ".$zero;
                      }
                    ?>
                </div>
                <div class="item4"><a href="lateReturned.php"><input type="button" class="check" value="Check"/></a></div>
            </div>
        </div>
    </body>
</html>
